version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: typedoc
    versions:
    - ">= 0"
  - dependency-name: delay
    versions:
    - 4.4.1
    - 5.0.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@babel/node"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 9.2.4
  - dependency-name: type-fest
    versions:
    - 0.21.0
    - 0.21.1
    - 0.21.2
    - 0.21.3
    - 1.0.0
    - 1.0.1
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.8
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
  - dependency-name: typescript
    versions:
    - 3.9.8
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
  registries:
  - npm-registry-registry-npmjs-org
